import bcrypt from "bcryptjs";

const PERSON_TYPES = [
  { value: "candidat", label: "Candidat" },
  { value: "recruteur", label: "Recruteur" },
  { value: "admin", label: "Admin" },
];

const CONTRACT_TYPES = [
  { value: "cdi", label: "CDI" },
  { value: "cdd", label: "CDD" },
  { value: "interim", label: "Intérim" },
  { value: "stage", label: "Stage" },
  { value: "alternance", label: "Alternance" },
  { value: "freelance", label: "Freelance" },
];

const WORKING_TIMES = [
  { value: "temps_plein", label: "Temps plein" },
  { value: "temps_partiel", label: "Temps partiel" },
];

const EXPERIENCE_LEVELS = [
  { value: "non_precise", label: "Non précisé" },
  { value: "debutant", label: "Débutant" },
  { value: "intermediaire", label: "Intermédiaire" },
  { value: "confirme", label: "Confirmé" },
  { value: "expert", label: "Expert" },
];

const REMOTE_OPTIONS = [
  { value: "non", label: "Aucun" },
  { value: "hybride", label: "Hybride" },
  { value: "full_remote", label: "Full remote" },
];

const AD_STATUSES = [
  { value: "active", label: "Active" },
  { value: "fermee", label: "Fermée" },
  { value: "brouillon", label: "Brouillon" },
];

const APPLICATION_STATUSES = [
  { value: "recu", label: "Reçue" },
  { value: "a_appeler", label: "À appeler" },
  { value: "a_recevoir", label: "À recevoir" },
  { value: "refuse", label: "Refusée" },
  { value: "recrute", label: "Recruté" },
];

const APPLICATION_LOG_EVENTS = [
  { value: "email", label: "Email" },
  { value: "call", label: "Appel" },
  { value: "message", label: "Message" },
  { value: "status_change", label: "Changement de statut" },
  { value: "note", label: "Note" },
];

const APPLICATION_LOG_DIRECTIONS = [
  { value: "out", label: "Sortant" },
  { value: "in", label: "Entrant" },
];

export const ADMIN_TABLES = {
  people: {
    label: "Utilisateurs",
    description: "Gérez les comptes candidats, recruteurs et administrateurs.",
    primaryKey: "person_id",
    defaultSort: [{ column: "created_at", direction: "DESC" }],
    searchColumns: ["first_name", "last_name", "email"],
    fields: [
      {
        name: "person_id",
        label: "ID",
        type: "readonly",
        showInTable: true,
      },
      {
        name: "first_name",
        label: "Prénom",
        type: "text",
        required: true,
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "last_name",
        label: "Nom",
        type: "text",
        required: true,
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        required: true,
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "password",
        label: "Mot de passe",
        type: "password",
        required: false,
        showInTable: false,
        creatable: true,
        editable: true,
        specialHandler: async (value) => {
          if (!value) return null;
          const hash = await bcrypt.hash(value, 10);
          return { column: "password_hash", value: hash };
        },
      },
      {
        name: "phone",
        label: "Téléphone",
        type: "text",
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "linkedin_url",
        label: "LinkedIn",
        type: "url",
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "person_type",
        label: "Rôle",
        type: "select",
        options: PERSON_TYPES,
        required: true,
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "is_active",
        label: "Actif",
        type: "boolean",
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "company_id",
        label: "ID entreprise",
        type: "number",
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "position",
        label: "Poste",
        type: "text",
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "created_at",
        label: "Créé le",
        type: "datetime",
        showInTable: true,
        creatable: false,
        editable: false,
      },
      {
        name: "updated_at",
        label: "Mis à jour le",
        type: "datetime",
        showInTable: false,
        creatable: false,
        editable: false,
      },
    ],
  },
  companies: {
    label: "Entreprises",
    description: "Catalogue des entreprises partenaires.",
    primaryKey: "company_id",
    defaultSort: [{ column: "company_name", direction: "ASC" }],
    searchColumns: ["company_name", "city", "industry", "email"],
    fields: [
      { name: "company_id", label: "ID", type: "readonly", showInTable: true },
      {
        name: "company_name",
        label: "Nom",
        type: "text",
        required: true,
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "industry",
        label: "Secteur",
        type: "text",
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "company_size",
        label: "Taille",
        type: "text",
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "website",
        label: "Site web",
        type: "url",
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "address",
        label: "Adresse",
        type: "textarea",
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "city",
        label: "Ville",
        type: "text",
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "country",
        label: "Pays",
        type: "text",
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "logo_url",
        label: "Logo (URL)",
        type: "url",
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "created_at",
        label: "Créée le",
        type: "datetime",
        showInTable: true,
        creatable: false,
        editable: false,
      },
      {
        name: "updated_at",
        label: "Mise à jour le",
        type: "datetime",
        showInTable: false,
        creatable: false,
        editable: false,
      },
    ],
  },
  advertisements: {
    label: "Annonces",
    description: "Offres d'emploi publiées sur la plateforme.",
    primaryKey: "ad_id",
    defaultSort: [{ column: "created_at", direction: "DESC" }],
    searchColumns: ["job_title", "location", "contract_type", "status"],
    fields: [
      { name: "ad_id", label: "ID", type: "readonly", showInTable: true },
      {
        name: "company_id",
        label: "ID entreprise",
        type: "number",
        required: true,
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "contact_person_id",
        label: "ID contact",
        type: "number",
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "job_title",
        label: "Titre",
        type: "text",
        required: true,
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "job_description",
        label: "Description",
        type: "textarea",
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "requirements",
        label: "Exigences",
        type: "textarea",
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "location",
        label: "Localisation",
        type: "text",
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "contract_type",
        label: "Contrat",
        type: "select",
        options: CONTRACT_TYPES,
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "working_time",
        label: "Temps de travail",
        type: "select",
        options: WORKING_TIMES,
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "experience_level",
        label: "Niveau d'expérience",
        type: "select",
        options: EXPERIENCE_LEVELS,
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "remote_option",
        label: "Télétravail",
        type: "select",
        options: REMOTE_OPTIONS,
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "salary_min",
        label: "Salaire min",
        type: "number",
        step: "0.01",
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "salary_max",
        label: "Salaire max",
        type: "number",
        step: "0.01",
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "currency",
        label: "Devise",
        type: "text",
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "deadline_date",
        label: "Date limite",
        type: "date",
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "status",
        label: "Statut",
        type: "select",
        options: AD_STATUSES,
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "created_at",
        label: "Créée le",
        type: "datetime",
        showInTable: true,
        creatable: false,
        editable: false,
      },
      {
        name: "updated_at",
        label: "Mise à jour le",
        type: "datetime",
        showInTable: false,
        creatable: false,
        editable: false,
      },
    ],
  },
  applications: {
    label: "Candidatures",
    description: "Suivi des candidatures déposées.",
    primaryKey: "application_id",
    defaultSort: [{ column: "created_at", direction: "DESC" }],
    searchColumns: ["status", "notes"],
    fields: [
      {
        name: "application_id",
        label: "ID",
        type: "readonly",
        showInTable: true,
      },
      {
        name: "ad_id",
        label: "ID annonce",
        type: "number",
        required: true,
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "person_id",
        label: "ID candidat",
        type: "number",
        required: true,
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "application_date",
        label: "Date de candidature",
        type: "datetime",
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "cover_letter",
        label: "Lettre de motivation",
        type: "textarea",
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "notes",
        label: "Notes",
        type: "textarea",
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "cv_path",
        label: "CV (lien)",
        type: "text",
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "status",
        label: "Statut",
        type: "select",
        options: APPLICATION_STATUSES,
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "created_at",
        label: "Créée le",
        type: "datetime",
        showInTable: true,
        creatable: false,
        editable: false,
      },
      {
        name: "updated_at",
        label: "Mise à jour le",
        type: "datetime",
        showInTable: false,
        creatable: false,
        editable: false,
      },
    ],
  },
  application_logs: {
    label: "Historique candidatures",
    description: "Journal des interactions liées aux candidatures.",
    primaryKey: "log_id",
    defaultSort: [{ column: "occurred_at", direction: "DESC" }],
    searchColumns: ["subject", "event_type", "direction"],
    fields: [
      { name: "log_id", label: "ID", type: "readonly", showInTable: true },
      {
        name: "application_id",
        label: "ID candidature",
        type: "number",
        required: true,
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "event_type",
        label: "Type d'événement",
        type: "select",
        required: true,
        options: APPLICATION_LOG_EVENTS,
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "direction",
        label: "Direction",
        type: "select",
        options: APPLICATION_LOG_DIRECTIONS,
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "subject",
        label: "Sujet",
        type: "text",
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "body",
        label: "Contenu",
        type: "textarea",
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "occurred_at",
        label: "Survenu le",
        type: "datetime",
        showInTable: true,
        creatable: true,
        editable: true,
      },
      {
        name: "meta",
        label: "Meta (JSON)",
        type: "textarea",
        showInTable: false,
        creatable: true,
        editable: true,
      },
      {
        name: "created_by_person_id",
        label: "Créé par (person_id)",
        type: "number",
        showInTable: true,
        creatable: true,
        editable: true,
      },
    ],
  },
};

export function getTableConfig(table) {
  return ADMIN_TABLES[table] ?? null;
}
